### ISSUE TITLE
添加itemsadder支持

### ISSUE THREAD

**Issue by TATyKeFei** [LSDog/CustomSprays#9]
希望能添加itemsadder支持
他可以在没有mod的情况下添加自定义物品模型创建物品贴图
这样就可以给喷漆灌添加物品模型贴图了而不是使用原版的物品来代替喷漆灌

这是itemsadder插件的地址
```
https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/
```

我很需要这个来美化我的服务器，谢谢

**Comment by LSDog** [comment]
这倒是好的，但是有一个小问题——我没买过也没用过这个插件，加上目前我会很忙没有时间，所以可能会很久之后才能实现这个功能

**Comment by postyizhan** [comment]
我做了ia支持
https://github.com/postyizhan/CustomSprays/tree/ia_resource

**Comment by postyizhan** [comment]
> 这倒是好的，但是有一个小问题——我没买过也没用过这个插件，加上目前我会很忙没有时间，所以可能会很久之后才能实现这个功能

我做了ia配置
您开一个新的分支，好让我给您提交pr？
https://github.com/postyizhan/CustomSprays/tree/ia_resource

**Comment by LSDog** [comment]
> 您开一个新的分支，好让我给您提交pr？

好的开了 是 [https://github.com/LSDog/CustomSprays/tree/itemsadder](itemsadder)

**Comment by postyizhan** [comment]
> > 您开一个新的分支，好让我给您提交pr？
> 
> 好的开了 是 [itemsadder](https://github.com/LSDog/CustomSprays/tree/itemsadder)

https://github.com/LSDog/CustomSprays/pull/10

**Comment by LSDog** [comment]
感谢 @postyizhan  ！

**Comment by TATyKeFei** [comment]
支持了，但是没完全支持。这个好像只是把音效资源包和ia合并了，但是我想要的是喷漆灌自定义物品模型功能QAQ

**Comment by LSDog** [comment]
> 支持了，但是没完全支持。这个好像只是把音效资源包和ia合并了，但是我想要的是喷漆灌自定义物品模型功能QAQ

@postyizhan 你有时间的话再看一下？我不会整

**Comment by postyizhan** [comment]
> 支持了，但是没完全支持。这个好像只是把音效资源包和ia合并了，但是我想要的是喷漆灌自定义物品模型功能QAQ

可是这个包本来就没有模型用呀
你说的模型是指什么，json模型？还是只是给换个贴图？

**Comment by postyizhan** [comment]
你想要给喷漆罐换上ia材质？可是这根本不需要CustomSprays方面去做呀。。。

### 例子：

#### ia配置
```
items:
  你的物品:
    resource:
      material: 1
      generate: true
      model_id: cmd值
      textures:
        - 材质地址
```
#### 物品库(NeigeItems为例)
```
test1:
  material: GOLDEN_HORSE_ARMOR
  custommodeldata: 114514
  name: '名字'
  lore:
  - '§e§l剩余使用 | Remaining use: §e§l20'
```

（自己测试的时候发现CustomSprays是直接读lore的。。。存nbt里不好吗
